[app]
  name = "devcloud"
  description = "app desc"
  address = "http://127.0.0.1:8080"
  encrypt_key = "defualt app encrypt key"

[datasource]
  provider = "mysql"
  host = "127.0.0.1"
  port = 3306
  database = "devcloud_go18"
  username = "root"
  password = "123456"
  auto_migrate = false
  debug = false

[mongo]
  endpoints = ["127.0.0.1:27017"]
  username = ""
  password = ""
  database = "devcloud_go18"

[kafka]
  brokers = ["127.0.0.1:9092"]
  username = ""
  password = ""

[http]
  host = "127.0.0.1"
  port = 8080
  path_prefix = "api"